# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 02:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pointset',
            old_name='data',
            new_name='date',
        ),
    ]
